title: "BELIEVE-It's me!"
email: rohitrajrrr29@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello Buddy!
baseurl: "/" 
url: "https://rraj29.github.io/" 
linkedin_username: certifieddatascientist
github_username:  rraj29

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
